version: "3"
services:

  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - "3031:3031"
    environment:
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      CHANNEL_TOKEN: ${CHANNEL_TOKEN}
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "8000:80"
    environment:
      TZ: "Asia/Tokyo"
      VIRTUAL_HOST: woodbot.wild-family.cf

networks:
    default:
        external:
          name: my_network
